---
- name: Check if node is initialized
  stat: path=/etc/kubernetes/kubelet.conf
  register: kubelet_conf
  when: "'k8s_other_masters' in group_names"

- name: Check if the first control node is in Ready state
  shell: kubectl get nodes | grep -w {{ ansible_hostname }} | grep -w Ready
  register: master_ready
  until: master_ready.stdout.find('Ready') != -1
  retries: 5
  delay: 10
  when: "'k8s_master' in group_names"
  

- name: Get certificate key
  shell: kubeadm init phase upload-certs --upload-certs 2>/dev/null | tail -n 1
  register: cert_key
  when: "'k8s_master' in group_names and master_ready.stdout.find('Ready') != -1"

- name: Get join command from main control plane
  shell: kubeadm token create --print-join-command
  register: join_command
  when: "'k8s_master' in group_names and master_ready.stdout.find('Ready') != -1"

- name: Join other control plane node to the cluster
  shell: "{{ hostvars[groups['k8s_master'][0]]['join_command']['stdout'] }} --control-plane --certificate-key {{ hostvars[groups['k8s_master'][0]]['cert_key']['stdout'] }}"
  when: "'k8s_other_masters' in group_names"

- name: Copy kube-vip manifest to remaining control plane nodes
  template:
    src: kube-vip.yaml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
  when: "'k8s_other_masters' in group_names"