---

- name: Import vars according to OS
  include_vars: "{{ ansible_os_family }}.yml"

- name: Sysctl setup
  include_tasks: sysctl.yml

- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Setup container runtime CRI-O
  include_tasks: crio.yml
  when: container_runtime == 'crio'

- name: Setup container runtime containerd
  include_tasks: containerd.yml
  when: container_runtime == 'containerd'

- name: Install Kubernetes packages
  include_tasks: Install-packages.yml

- name: Initialize Kubernetes on first master node
  include_tasks: control-plane.yml
  when: "'k8s_master' in group_names"

- name: Join other master nodes
  include_tasks: join-control-plane.yml
  when: ("'k8s_master_other' in group_names") and (VIP != "")

- name: Setup Worker Node
  include_tasks: worker-node.yml

- name: Install MetalLB
  include_tasks: metallb.yml
  when: (metallb_ip_range != "") and ("'k8s_master' in group_names")

- name: Print cluster details
  include_tasks: print.yml
  when: "'k8s_master' in group_names"