---

- name: Import vars according to OS
  include_vars: "{{ ansible_os_family }}.yml"

- name: Sysctl setup
  include_tasks: sysctl.yml

- include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Setup container runtime CRI-O
  include_tasks: crio.yml
  when: container_runtime == 'crio'

- name: Setup container runtime containerd
  include_tasks: containerd.yml
  when: container_runtime == 'containerd'

- name: Install Kubernetes packages
  include_tasks: Install-packages.yml

- name: Setup Control Plane
  include_tasks: control-plane.yml
  when: "'k8s_master' in group_names"

- name: Setup Worker Node
  include_tasks: worker-node.yml

- name: Install MetalLB
  include_tasks: metallb.yml
  when: metallb_ip_range != ""