---
- name: Ensure all packages are up to date
  yum:
    name: '*'
    state: latest
  args:
    update_cache: yes

- name: Disable SELinux
  selinux:
    state: disabled

- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true

- name: Add Kubernetes repo
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    baseurl: "{{ kubernetes_yum_base_url }}"
    gpgkey: "{{ kubernetes_yum_gpg_key }}"
    state: present

- name: Add Kubernetes GPG keys.
  rpm_key:
    key: "{{ kubernetes_yum_gpg_key }}"
    state: present

- name: Update yum cache
  yum:
    update_cache: yes